# This is a basic workflow to help you get started with Actions

name: Build new phyzess.me

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PHYZESS_NOTION_TOKEN: ${{ secrets.PHYZESS_NOTION_TOKEN }}
      PHYZESS_SITE_CONFIG_URL: ${{ secrets.PHYZESS_SITE_CONFIG_URL }}
      PHYZESS_POST_LIST_URL: ${{ secrets.PHYZESS_POST_LIST_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn run install

    - name: Build phyzess.me
      run: yarn run build
